### ISSUE TITLE
Issue with Betterfoliage

### ISSUE THREAD

**Issue by brandyyn** [FalsePattern/FalseTweaks#151]
This is spamming my logs, an issue with the new chunk renderer + betterfoliage?

> [18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reflector.callBoolean(Reflector.java:223)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:359)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.falsepattern.falsetweaks.modules.threadedupdates.ThreadedChunkUpdateHelper.doChunkUpdate(ThreadedChunkUpdateHelper.java:342)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.falsepattern.falsetweaks.modules.threadedupdates.ThreadedChunkUpdateHelper.runThread(ThreadedChunkUpdateHelper.java:281)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.falsepattern.falsetweaks.modules.threadedupdates.ThreadedChunkUpdateHelper.lambda$spawnThreads$0(ThreadedChunkUpdateHelper.java:184)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Thread.run(Unknown Source)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.IllegalStateException: Tried to access main tessellator from non-main thread Chunk Update Worker Thread #0
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.Tessellator.verifyThreadIsCorrect(Tessellator.java:1897)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.Tessellator.handler$zfd000$falsetweaks$verifyThreadIsCorrect(Tessellator.java:1882)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.Tessellator.func_78380_c(Tessellator.java)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mods.octarinecore.client.render.ModelRenderer.render(ModelRenderer.kt:54)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mods.octarinecore.client.render.ModelRenderer.render$default(ModelRenderer.kt:35)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mods.betterfoliage.client.render.RenderLeaves.render(RenderLeaves.kt:51)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mods.octarinecore.client.render.AbstractBlockRenderingHandler.renderWorldBlock(AbstractBlockRenderingHandler.kt:55)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
[18:06:01] [Chunk Update Worker Thread #0/INFO] [STDERR/falsetweaks]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 9 more

can't attach the log because it's spamming this to the point my log is over 250mb at the point i closed my game..

**Comment by brandyyn** [comment]
![image](https://github.com/FalsePattern/FalseTweaks/assets/11356565/c8180593-dcdc-4687-b834-339a0dac6cb3)

it ended up corrupting my log and freezing my game

**Comment by FalsePattern** [comment]
Ah, better foliage is not compatible with threaded rendering.
Will be fixed in the next update.
