### ISSUE TITLE
[3.0.1]Crash with AcademyCraft 1.0.7b(and LambdaLib-1.2.3)

### ISSUE THREAD

**Issue by Twilight2** [FalsePattern/FalseTweaks#185]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-07-19 21:25:57 CST
Description: Initializing game

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/Tessellator
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4593)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/Tessellator
    at cn.lambdalib.template.client.render.item.RenderModelItem.<init>(RenderModelItem.java:41)
    at cn.academy.ability.client.render.RenderDeveloperPortable.<init>(RenderDeveloperPortable.java:20)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cn.lambdalib.annoreg.core.RegistryHelper.getFieldFromObject(RegistryHelper.java:109)
    at cn.lambdalib.annoreg.mc.ItemRegistration$3.invoke(ItemRegistration.java:49)
    at cn.lambdalib.annoreg.mc.ItemRegistration$3.invoke(ItemRegistration.java:44)
    at cn.lambdalib.annoreg.core.RegistrationWithPostWork.doPostRegWork(RegistrationWithPostWork.java:47)
    at cn.lambdalib.annoreg.base.RegistrationFieldSimple.registerField(RegistrationFieldSimple.java:59)
    at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:148)
    at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:149)
    at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
    at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:83)
    at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:149)
    at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
    at cn.academy.core.AcademyCraft.preInit(AcademyCraft.java:93)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.Tessellator
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 55 more

**Comment by FalsePattern** [comment]
Send the `fml_client_latest.log` file.

**Comment by Twilight2** [comment]
> Send the `fml_client_latest.log` file.

I searched the whole .minecraft, but didn't find it.
[latest.log](https://github.com/user-attachments/files/16313178/latest.log)

**Comment by Twilight2** [comment]
> Send the `fml_client_latest.log` file.

And everything works fine with falsetweaks-mc1.7.10-2.2.1

**Comment by FalsePattern** [comment]
Neodymium Unofficial only works with FalseTweaks 3.0 or newer.

Does the crash stop happening when you remove AcademyCraft and LambdaLib? Try removing mods one by one from your modpack until this crash stops, and then tell me which mod specifically breaks with FalseTweaks. Your modpack is too large for me to diagnose from the log.

**Comment by FalsePattern** [comment]
Some other mod is modifying the minecraft renderer code in a way that is incompatible with FalseTweaks.

**Comment by FalsePattern** [comment]
Also, please make sure your .minecraft folder and mod jar files only have alphanumeric characters in them (a-z, A-Z, 0-9), having non-latin characters in the file names breaks mod detection

**Comment by FalsePattern** [comment]
I have found the source of the issue, I am working on a fix.

**Comment by Twilight2** [comment]
Thank you!
And I already delete 5 mods but the game still crash with the "Tessellator" issue...

**Comment by FalsePattern** [comment]
The issue was that FalsePatternLib's mixin loader logic used by FalseTweaks was not prepared to work on non-English file names, i'm implementing a workaround for it right now.

**Comment by FalsePattern** [comment]
Please update FalsePatternLib to 1.4.0, and then test if this FalseTweaks jar fixes the crash:
https://mvn.falsepattern.com/releases/com/falsepattern/falsetweaks-mc1.7.10/3.0.1-1-gf2cc929/falsetweaks-mc1.7.10-3.0.1-1-gf2cc929.jar

**Comment by Twilight2** [comment]
> Please update FalsePatternLib to 1.4.0, and then test if this FalseTweaks jar fixes the crash: https://mvn.falsepattern.com/releases/com/falsepattern/falsetweaks-mc1.7.10/3.0.1-1-gf2cc929/falsetweaks-mc1.7.10-3.0.1-1-gf2cc929.jar

Still crash,and I didn't change the file name this time.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-07-19 23:43:56 CST
Description: Initializing game

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/Tessellator
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4093)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/Tessellator
    at cn.lambdalib.template.client.render.item.RenderModelItem.<init>(RenderModelItem.java:41)
    at cn.academy.ability.client.render.RenderDeveloperPortable.<init>(RenderDeveloperPortable.java:20)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cn.lambdalib.annoreg.core.RegistryHelper.getFieldFromObject(RegistryHelper.java:109)
    at cn.lambdalib.annoreg.mc.ItemRegistration$3.invoke(ItemRegistration.java:49)
    at cn.lambdalib.annoreg.mc.ItemRegistration$3.invoke(ItemRegistration.java:44)
    at cn.lambdalib.annoreg.core.RegistrationWithPostWork.doPostRegWork(RegistrationWithPostWork.java:47)
    at cn.lambdalib.annoreg.base.RegistrationFieldSimple.registerField(RegistrationFieldSimple.java:59)
    at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:148)
    at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:149)
    at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
    at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:83)
    at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:149)
    at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
    at cn.academy.core.AcademyCraft.preInit(AcademyCraft.java:93)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.Tessellator
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 55 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
    at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 57 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.falsetweaks.json:client.bsp.foamfix.TessellatorBSPSortingMixin from mod falsetweaks] from phase [DEFAULT] in config [mixins.falsetweaks.json] FAILED during APPLY
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
    ... 62 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on bspSort could not find any targets matching 'getVertexState_foamfix_old' in net.minecraft.client.renderer.Tessellator. Using refmap mixins.falsetweaks.refmap.json [PREINJECT Applicator Phase -> mixins.falsetweaks.json:client.bsp.foamfix.TessellatorBSPSortingMixin from mod falsetweaks -> Prepare Injections ->  -> handler$zgc000$falsetweaks$bspSort(FFFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658)
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589)
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
    at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
    at sun.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
    at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
    at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
    ... 62 more

**Comment by FalsePattern** [comment]
Try removing foamfix

**Comment by FalsePattern** [comment]
Try this jar, it should fix this second crash too
https://mvn.falsepattern.com/releases/com/falsepattern/falsetweaks-mc1.7.10/3.0.1-2-g0136451/falsetweaks-mc1.7.10-3.0.1-2-g0136451.jar

**Comment by Twilight2** [comment]
> Try this jar, it should fix this second crash too https://mvn.falsepattern.com/releases/com/falsepattern/falsetweaks-mc1.7.10/3.0.1-2-g0136451/falsetweaks-mc1.7.10-3.0.1-2-g0136451.jar

Yes!Now everthing works fine even I changed the file name and start with Foamfix.
Thanks a lot!

**Comment by FalsePattern** [comment]
Does this still happen with 3.5.x?
