### ISSUE TITLE
[3.1.1] HBM crash  ArrayIndexOutOfBoundsException Tesselator

### ISSUE THREAD

**Issue by Goosegit11** [FalsePattern/FalseTweaks#189]
```
[22:04:19] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 8/18/24 10:04 PM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 65536
	at net.minecraft.client.renderer.Tessellator.func_78377_a(Tessellator.java:368)
	at net.minecraft.client.renderer.RenderGlobal.<init>(RenderGlobal.java:192)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:538)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.Tessellator.func_78377_a(Tessellator.java:368)
	at net.minecraft.client.renderer.RenderGlobal.<init>(RenderGlobal.java:192)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:538)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

```

**Comment by Knewest** [comment]
Is 'HodgePodge' enabled? I had this issue till I figured out disabling that fixed it. Although, 'HodgePodge' comes with Greg Tech: New Horizons.

**Comment by Goosegit11** [comment]
No HodgePodge

**Comment by Knewest** [comment]
Apologies, I forgot to update this. Here were my findings: https://github.com/FalsePattern/FalseTweaks/issues/191

Setting `B:THREADED_CHUNK_UPDATES` and `B:BSP_SORTING` in the config to false fixed all the issues for me and allowed HodgePodge to work.

**Comment by FalsePattern** [comment]
Should be fixed in the latest version
