### ISSUE TITLE
Techguns incompatible GL state for ladder(this generates with its structures)

### ISSUE THREAD

**Issue by brandyyn** [FalsePattern/FalseTweaks#200]
Techguns incompatible GL state for ladder(this generates with its structures)

[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.RuntimeException: No OpenGL context found in the current thread.
[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at org.lwjgl.opengl.GL13.glMultiTexCoord2f(GL13.java:320)
[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at net.minecraft.client.renderer.OpenGlHelper.zamnza(OpenGlHelper.java:950)
[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at net.minecraft.client.renderer.OpenGlHelper.redirect$znj000$testA(OpenGlHelper.java:935)
[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at net.minecraft.client.renderer.OpenGlHelper.func_77475_a(OpenGlHelper.java:750)
[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at com.falsepattern.rple.internal.mixin.extension.ExtendedOpenGlHelper.setLightMapTextureCoordsRGB64(ExtendedOpenGlHelper.java:57)
[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at net.minecraft.client.renderer.OpenGlHelper.handler$znj000$onSet(OpenGlHelper.java:909)
[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at net.minecraft.client.renderer.OpenGlHelper.func_77475_a(OpenGlHelper.java)
[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at techguns.client.renderer.block.RenderLadder.adjustLightFixture(RenderLadder.java:193)
[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at techguns.client.renderer.block.RenderLadder.renderWorldBlock(RenderLadder.java:61)
[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
[21:30:35] [$LUMI_NO_RELIGHTChunk Update Worker #0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)

**Comment by brandyyn** [comment]
![image](https://github.com/user-attachments/assets/b6417f00-a695-4391-b02c-817e3ab0dd2d)
the ladders make the chunks completely stop rendering

**Comment by FalsePattern** [comment]
Fixed in 3.5.1
