### ISSUE TITLE
Crash when use shaders

### ISSUE THREAD

**Issue by kotmatross28729** [FalsePattern/FalseTweaks#40]
`---- Minecraft Crash Report ----
// My bad.

Time: 25.09.22 10:27
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: -5
	at shadersmod.client.ShadersTess.addVertex(ShadersTess.java:347)
	at net.minecraft.client.renderer.Tessellator.func_78377_a(Tessellator.java:604)
	at net.minecraft.client.renderer.Tessellator.func_78374_a(Tessellator.java:592)
	at net.minecraft.client.renderer.RenderBlocks.func_147761_c(RenderBlocks.java:8382)
	at net.minecraft.client.renderer.RenderBlocks$$Lambda$217/2104022283.render(Unknown Source)
	at net.minecraft.client.renderer.RenderBlocks.renderFace(RenderBlocks.java:10140)
	at net.minecraft.client.renderer.RenderBlocks.renderWithAO(RenderBlocks.java:10179)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:10704)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4784)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:327)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:325)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2382)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1657)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1392)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at shadersmod.client.ShadersTess.addVertex(ShadersTess.java:347)
	at net.minecraft.client.renderer.Tessellator.func_78377_a(Tessellator.java:604)
	at net.minecraft.client.renderer.Tessellator.func_78374_a(Tessellator.java:592)
	at net.minecraft.client.renderer.RenderBlocks.func_147761_c(RenderBlocks.java:8382)
	at net.minecraft.client.renderer.RenderBlocks$$Lambda$217/2104022283.render(Unknown Source)
	at net.minecraft.client.renderer.RenderBlocks.renderFace(RenderBlocks.java:10140)
	at net.minecraft.client.renderer.RenderBlocks.renderWithAO(RenderBlocks.java:10179)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:10704)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4784)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:327)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:325)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2382)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1657)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Kot'/282, l='MpServer', x=-245,27, y=67,72, z=193,99]]
	Chunk stats: MultiplayerChunkCache: 521, 530
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-256,64,216), Chunk: (at 0,4,8 in -16,13; contains blocks -256,0,208 to -241,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 235 game time, 235 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 52 total; [EntitySquid['Squid'/128, l='MpServer', x=-240,84, y=55,34, z=164,69], EntitySquid['Squid'/129, l='MpServer', x=-231,88, y=53,89, z=171,42], EntitySquid['Squid'/130, l='MpServer', x=-229,72, y=50,84, z=172,50], EntitySquid['Squid'/131, l='MpServer', x=-233,50, y=54,34, z=164,88], EntitySquid['Squid'/132, l='MpServer', x=-226,79, y=47,82, z=218,67], EntityClientPlayerMP['Zerofogy'/282, l='MpServer', x=-245,27, y=67,72, z=193,99], EntityBat['Bat'/161, l='MpServer', x=-218,69, y=16,00, z=140,34], EntityBat['Bat'/162, l='MpServer', x=-215,22, y=16,00, z=142,41], EntitySquid['Squid'/163, l='MpServer', x=-210,75, y=58,34, z=143,59], EntitySquid['Squid'/164, l='MpServer', x=-222,06, y=55,13, z=136,56], EntityBat['Bat'/165, l='MpServer', x=-215,84, y=37,00, z=147,59], EntityBat['Bat'/166, l='MpServer', x=-215,97, y=39,14, z=146,28], EntitySquid['Squid'/167, l='MpServer', x=-211,25, y=57,66, z=150,06], EntitySquid['Squid'/168, l='MpServer', x=-221,59, y=56,34, z=140,38], EntitySquid['Squid'/40, l='MpServer', x=-306,09, y=47,75, z=137,69], EntitySquid['Squid'/169, l='MpServer', x=-213,78, y=54,34, z=145,34], EntitySquid['Squid'/41, l='MpServer', x=-306,37, y=47,65, z=135,82], EntitySquid['Squid'/170, l='MpServer', x=-215,03, y=61,31, z=161,03], EntitySquid['Squid'/171, l='MpServer', x=-214,06, y=61,31, z=165,16], EntitySquid['Squid'/43, l='MpServer', x=-306,25, y=46,94, z=155,66], EntitySquid['Squid'/172, l='MpServer', x=-215,09, y=45,38, z=223,14], EntityBat['Bat'/44, l='MpServer', x=-308,84, y=18,00, z=239,88], EntitySquid['Squid'/173, l='MpServer', x=-221,48, y=45,76, z=221,66], EntitySquid['Squid'/174, l='MpServer', x=-213,56, y=48,36, z=220,40], EntitySquid['Squid'/52, l='MpServer', x=-293,75, y=44,72, z=161,16], EntitySquid['Squid'/53, l='MpServer', x=-299,56, y=50,38, z=151,97], EntitySquid['Squid'/54, l='MpServer', x=-294,66, y=48,13, z=161,38], EntityBat['Bat'/55, l='MpServer', x=-302,69, y=24,14, z=234,59], EntityBat['Bat'/56, l='MpServer', x=-289,47, y=20,17, z=239,72], EntityBat['Bat'/57, l='MpServer', x=-284,47, y=15,99, z=246,34], EntitySquid['Squid'/191, l='MpServer', x=-202,25, y=60,25, z=166,28], EntitySquid['Squid'/192, l='MpServer', x=-190,66, y=58,38, z=212,13], EntitySquid['Squid'/193, l='MpServer', x=-189,44, y=56,38, z=214,50], EntitySquid['Squid'/194, l='MpServer', x=-194,38, y=42,75, z=231,41], EntitySquid['Squid'/195, l='MpServer', x=-194,50, y=46,28, z=235,19], EntitySquid['Squid'/196, l='MpServer', x=-193,53, y=46,88, z=249,34], EntitySquid['Squid'/197, l='MpServer', x=-196,53, y=61,34, z=248,84], EntitySquid['Squid'/198, l='MpServer', x=-197,59, y=61,38, z=251,25], EntityBat['Bat'/72, l='MpServer', x=-275,47, y=15,95, z=242,09], EntitySquid['Squid'/200, l='MpServer', x=-188,69, y=57,22, z=212,13], EntitySquid['Squid'/201, l='MpServer', x=-190,34, y=56,75, z=218,22], EntitySquid['Squid'/202, l='MpServer', x=-190,38, y=44,34, z=235,09], EntitySquid['Squid'/203, l='MpServer', x=-182,75, y=55,34, z=229,19], EntitySquid['Squid'/204, l='MpServer', x=-183,28, y=53,00, z=236,63], EntitySquid['Squid'/206, l='MpServer', x=-186,16, y=55,34, z=238,31], EntitySquid['Squid'/207, l='MpServer', x=-189,03, y=60,00, z=240,25], EntitySquid['Squid'/208, l='MpServer', x=-186,28, y=58,03, z=251,25], EntitySquid['Squid'/106, l='MpServer', x=-241,88, y=52,19, z=137,22], EntityBat['Bat'/2420, l='MpServer', x=-224,56, y=15,86, z=121,72], EntitySquid['Squid'/125, l='MpServer', x=-233,16, y=52,38, z=134,22], EntityItem['item.item.seeds'/1534, l='MpServer', x=-265,37, y=63,13, z=215,16], EntitySquid['Squid'/126, l='MpServer', x=-241,50, y=48,34, z=140,06]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1057236184 bytes (1008 MB) / 2147483648 bytes (2048 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms2048M -Xmx6144M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 11, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{2.1.12-GTNH} [Not Enough Items] (notenoughitems-1.7.10-2.1.12-gtnh-universal.jar) 
	UCHIJAAAA	spongemixins{1.5.0} [SpongeMixins] (00gasstation-mc1.7.10-0.3.4.jar) 
	UCHIJAAAA	mixingasm{0.2.2} [Mixingasm] (00gasstation-mc1.7.10-0.3.4.jar) 
	UCHIJAAAA	mixinbooterlegacy{1.1.2} [MixinBooterLegacy] (00gasstation-mc1.7.10-0.3.4.jar) 
	UCHIJAAAA	gasstation{0.3.4} [GasStation] (00gasstation-mc1.7.10-0.3.4.jar) 
	UCHIJAAAA	falsepatternlib{0.10.10} [FalsePatternLib] (falsepatternlib-mc1.7.10-0.10.10.jar) 
	UCHIJAAAA	archaicfix{0.3.2} [Archaic Fix] (archaicfix-mc1.7.10-0.3.2 (1).jar) 
	UCHIJAAAA	backhand{1.7.10} [Backhand] (backhand-1.2.0.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (minetweaker3-1.7.10-3.0.10b.jar) 
	UCHIJAAAA	TwilightForest{2.3.8dev} [The Twilight Forest] (twilightforest-1.7.10-2.3.8.jar) 
	UCHIJAAAA	etfuturum{2.4.0} [§5§oEt Futurum Requiem] (Et_Futurum_Requiem-2.4.0.jar) 
	UCHIJAAAA	falsetweaks{2.0.0-alpha0003} [FalseTweaks] (falsetweaks-mc1.7.10-2.0.0-alpha0003.jar) 
	UCHIJAAAA	neiintegration{1.1.0} [NEI Integration] (NEIIntegration_MC1.7.10_1.1.0.jar) 
	UCHIJAAAA	VillageNames{4.4.1b} [§6Village Names] (VillageNames-1.7.10-4.4.1b.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit_forge_mc1.7.10_6.1.1_dist (1).jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 516.94' Renderer: 'NVIDIA GeForce GTX 750 Ti/PCIe/SSE2'
	Launched Version: Forge 1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.94, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [AVPBR-1-3.zip, NoZ-Fighting-v1.2.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)`

**Comment by FalsePattern** [comment]
Fixed in 2.0 Alpha 4
