### ISSUE TITLE
Crash when joining world

### ISSUE THREAD

**Issue by embeddedt** [FalsePattern/FalseTweaks#64]
I'm guessing there might be some sort of race condition with the AF threaded chunk updating? This occurs when TRIANGULATOR is enabled (the option that enables `RenderBlocksUltraMixin`).

```
[16:39:34] [Client thread/INFO] [STDOUT]: [makamys.coretweaks.tweak.crashhandler.CrashHandler:createCrashReport:44]: ---- Minecraft Crash Report ----
// Ooh. Shiny.
Time: 10/9/22 4:39 PM
Description: Unexpected error
java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.RenderBlocks.isBlacklisted(RenderBlocks.java:9553)
	at net.minecraft.client.renderer.RenderBlocks.handler$zgh000$exclusion(RenderBlocks.java:9565)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.rebuildChunks(RenderGlobal.java:2775)
	at net.minecraft.client.renderer.RenderGlobal.handler$zef000$performCullingUpdates(RenderGlobal.java:2842)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4000)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Stacktrace:
	at net.minecraft.client.renderer.RenderBlocks.isBlacklisted(RenderBlocks.java:9553)
	at net.minecraft.client.renderer.RenderBlocks.handler$zgh000$exclusion(RenderBlocks.java:9565)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.rebuildChunks(RenderGlobal.java:2775)
	at net.minecraft.client.renderer.RenderGlobal.handler$zef000$performCullingUpdates(RenderGlobal.java:2842)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['AWEChess1'/2921, l='MpServer', x=154.24, y=70.62, z=255.99]]
	Chunk stats: MultiplayerChunkCache: 5, 5
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (40,64,256), Chunk: (at 8,4,0 in 2,16; contains blocks 32,0,256 to 47,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 14959 game time, 1412 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 19 total; [EntityCreeper['Creeper'/2789, l='MpServer', x=132.50, y=69.00, z=271.50], EntitySkeleton['Skeleton'/2790, l='MpServer', x=130.50, y=69.00, z=271.50], EntityCreeper['Creeper'/2791, l='MpServer', x=129.50, y=69.00, z=269.50], EntityClientPlayerMP['AWEChess1'/2921, l='MpServer', x=154.24, y=70.62, z=255.99], EntityTFNagaSegment['unknown'/2991, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/2992, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/2993, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/2994, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/2995, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/2996, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityItem['item.item.bone'/2804, l='MpServer', x=149.06, y=67.13, z=246.84], EntityTFNagaSegment['unknown'/2997, l='MpServer', x=0.60, y=-0.24, z=0.60], EntitySkeleton['Skeleton'/2805, l='MpServer', x=154.56, y=67.00, z=260.34], EntityTFNagaSegment['unknown'/2998, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/2999, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/3000, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/3001, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/3002, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTrail['unknown'/3295, l='MpServer', x=154.24, y=70.62, z=255.99]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4020)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
```

**Comment by FalsePattern** [comment]
Known issue, will be fixed in the next beta, i just didn't have much time lately.

**Comment by GamebP** [comment]
is there a way to get around the crash?

**Comment by embeddedt** [comment]
As I mentioned in the issue, you can disable `TRIANGULATOR` in the FalseTweaks config.

**Comment by FalsePattern** [comment]
Closed as stale
